alphabetic:
  iPad:
    floating: "alphabeticPortrait"
    landscape: "alphabeticLandscape"
    portrait: "alphabeticPortrait"
  iPhone:
    landscape: "alphabeticLandscape"
    portrait: "alphabeticPortrait"
numeric:
  iPad:
    floating: "numericPortrait"
    landscape: "numericLandscape"
    portrait: "numericPortrait"
  iPhone:
    landscape: "numericLandscape"
    portrait: "numericPortrait"
panel:
  iPad:
    floating: "panelPortrait"
    landscape: "panelLandscape"
    portrait: "panelPortrait"
  iPhone:
    landscape: "panelLandscape"
    portrait: "panelPortrait"
pinyin:
  iPad:
    floating: "pinyinPortrait"
    landscape: "pinyinLandscape"
    portrait: "pinyinPortrait"
  iPhone:
    landscape: "pinyinLandscape"
    portrait: "pinyinPortrait"